# Generated by Django 2.1.4 on 2019-06-16 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='RaceFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='race.Race')),
            ],
        ),
        migrations.CreateModel(
            name='RaceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_from_start', models.FloatField()),
                ('acceleration', models.FloatField()),
                ('speed', models.FloatField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car.Car')),
                ('race_frame', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='race.RaceFrame')),
            ],
        ),
    ]
