# Generated by Django 2.1.4 on 2019-01-07 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracksector',
            options={'ordering': ['sector_order']},
        ),
    ]
