# Generated by Django 2.1.4 on 2019-01-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracksector',
            old_name='end',
            new_name='length',
        ),
        migrations.RemoveField(
            model_name='tracksector',
            name='start',
        ),
        migrations.AddField(
            model_name='tracksector',
            name='sector_order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
